owlFilePath: MPHPO_ontorel-slim_20240820.owl
loadEquivalentClass: false
annotations:
  labels:
    - "http://www.w3.org/2000/01/rdf-schema#label"
    - "http://purl.obolibrary.org/obo/BFO_0000179"
  definitions:
    - "http://www.w3.org/2000/01/rdf-schema#comment"
    - "http://purl.org/dc/elements/1.1/description"